--
-- V25__orders.sql
--
-- Unified orders and order items (Sprint 2, S2-US06).
--
-- Subtasks:
--    LEMBAS-244: Crear V25__orders.sql con orders y order_items
--    LEMBAS-249: Agregar constraints y tests de reglas ONLINE/POS
--
-- Note: the story references V5__orders.sql, but the project already applied
-- up to V24__pricing_batches.sql. A new incremental migration (V25) keeps the
-- Flyway linear history consistent for fresh and existing databases.
--

-- =============================================================================
-- Sequence used by OrderNumberGenerator to produce unique order_number values
-- =============================================================================
CREATE SEQUENCE order_number_seq START WITH 1 INCREMENT BY 1;

COMMENT ON SEQUENCE order_number_seq IS
    'Monotonically increasing sequence used by OrderNumberGenerator to keep order_number values unique.';

-- =============================================================================
-- Orders: unified entity for both POS and ONLINE sales
-- =============================================================================
CREATE TABLE orders (
    id                       BIGSERIAL       PRIMARY KEY,
    order_number             VARCHAR(50)     UNIQUE NOT NULL,
    type                     VARCHAR(20)     NOT NULL,
    status                   VARCHAR(30)     NOT NULL,
    branch_id                BIGINT          NOT NULL REFERENCES branches(id),
    customer_user_id         BIGINT          REFERENCES users(id),
    created_by_user_id       BIGINT          REFERENCES users(id),
    customer_name_snapshot   VARCHAR(255),
    customer_email_snapshot  VARCHAR(255),
    customer_phone_snapshot  VARCHAR(50),
    fulfillment_type         VARCHAR(20)     DEFAULT 'PICKUP' NOT NULL,
    subtotal                 DECIMAL(12, 2)  NOT NULL,
    discount_total           DECIMAL(12, 2)  DEFAULT 0 NOT NULL,
    total                    DECIMAL(12, 2)  NOT NULL,
    notes                    TEXT,
    paid_at                  TIMESTAMPTZ,
    prepared_at              TIMESTAMPTZ,
    delivered_at             TIMESTAMPTZ,
    cancelled_at             TIMESTAMPTZ,
    cancellation_reason      TEXT,
    created_at               TIMESTAMPTZ     DEFAULT now() NOT NULL,
    updated_at               TIMESTAMPTZ     DEFAULT now() NOT NULL,

    CONSTRAINT chk_orders_type
        CHECK (type IN ('POS', 'ONLINE')),
    CONSTRAINT chk_orders_status
        CHECK (status IN (
            'PENDING_PAYMENT',
            'PAID',
            'PREPARING',
            'READY',
            'DELIVERED',
            'CANCELLED',
            'PAYMENT_FAILED',
            'STOCK_CONFLICT'
        )),
    CONSTRAINT chk_orders_fulfillment_type
        CHECK (fulfillment_type IN ('PICKUP')),
    CONSTRAINT chk_orders_subtotal
        CHECK (subtotal >= 0),
    CONSTRAINT chk_orders_discount_total
        CHECK (discount_total >= 0),
    CONSTRAINT chk_orders_total
        CHECK (total >= 0),
    -- ONLINE orders must reference a registered customer; POS orders are created
    -- by an internal employee (created_by_user_id) and do not require a customer.
    CONSTRAINT chk_orders_online_requires_customer
        CHECK (
            type = 'POS'
            OR (type = 'ONLINE' AND customer_user_id IS NOT NULL)
        ),
    -- POS orders must have a cashier / employee; ONLINE orders do not.
    CONSTRAINT chk_orders_pos_requires_employee
        CHECK (
            (type = 'POS' AND created_by_user_id IS NOT NULL)
            OR type = 'ONLINE'
        ),
    -- POS orders can only ever reach PAID or CANCELLED (sales are completed at
    -- the moment of payment). ONLINE orders accept the full lifecycle.
    CONSTRAINT chk_orders_pos_status
        CHECK (
            (type = 'POS' AND status IN ('PAID', 'CANCELLED'))
            OR type = 'ONLINE'
        )
);

COMMENT ON TABLE orders IS
    'Unified order entity covering both in-store POS sales and online customer orders. The channel is captured by the type column.';
COMMENT ON COLUMN orders.type IS 'Channel: POS (in-store) or ONLINE (storefront).';
COMMENT ON COLUMN orders.status IS 'Lifecycle state. POS only reaches PAID or CANCELLED; ONLINE traverses the full payment + fulfillment lifecycle.';
COMMENT ON COLUMN orders.fulfillment_type IS 'Fulfillment mode. MVP only supports PICKUP at branch; DELIVERY can be added later by extending the CHECK constraint.';
COMMENT ON COLUMN orders.order_number IS 'Human-readable unique identifier (e.g. ON-20260612-000001) generated by OrderNumberGenerator.';
COMMENT ON COLUMN orders.customer_name_snapshot IS 'Customer full name snapshot taken at order creation; used for historical reports.';
COMMENT ON COLUMN orders.customer_email_snapshot IS 'Customer email snapshot taken at order creation.';
COMMENT ON COLUMN orders.customer_phone_snapshot IS 'Customer phone snapshot taken at order creation.';

-- =============================================================================
-- Order items: snapshot of product and price at the moment of sale
-- =============================================================================
CREATE TABLE order_items (
    id                       BIGSERIAL       PRIMARY KEY,
    order_id                 BIGINT          NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id               BIGINT          REFERENCES products(id),
    quantity                 DECIMAL(12, 3)  NOT NULL,
    unit_price               DECIMAL(12, 2)  NOT NULL,
    discount_amount          DECIMAL(12, 2)  DEFAULT 0 NOT NULL,
    subtotal_amount          DECIMAL(12, 2)  NOT NULL,
    product_name_snapshot    VARCHAR(255)    NOT NULL,
    product_barcode_snapshot VARCHAR(100),
    cost_price_snapshot      DECIMAL(12, 2),
    created_at               TIMESTAMPTZ     DEFAULT now() NOT NULL,

    CONSTRAINT chk_order_items_quantity
        CHECK (quantity > 0),
    CONSTRAINT chk_order_items_unit_price
        CHECK (unit_price >= 0),
    CONSTRAINT chk_order_items_discount_amount
        CHECK (discount_amount >= 0),
    CONSTRAINT chk_order_items_subtotal_amount
        CHECK (subtotal_amount >= 0)
);

COMMENT ON TABLE order_items IS
    'Line items for an order with immutable product and price snapshots. Snapshots keep reports stable even when catalog data changes later.';
COMMENT ON COLUMN order_items.product_name_snapshot IS 'Product name captured at sale time.';
COMMENT ON COLUMN order_items.product_barcode_snapshot IS 'Product barcode captured at sale time (optional).';
COMMENT ON COLUMN order_items.cost_price_snapshot IS 'Unit cost snapshot at sale time used for margin reports.';

-- =============================================================================
-- Indexes
-- =============================================================================
CREATE INDEX idx_orders_branch_created_at ON orders (branch_id, created_at DESC);
CREATE INDEX idx_orders_status             ON orders (status);
CREATE INDEX idx_orders_type               ON orders (type);
CREATE INDEX idx_orders_customer_user_id   ON orders (customer_user_id);
CREATE INDEX idx_orders_created_by_user_id ON orders (created_by_user_id);
CREATE INDEX idx_orders_status_type        ON orders (status, type);

CREATE INDEX idx_order_items_order_id   ON order_items (order_id);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);

-- =============================================================================
-- Link stock_movements.order_id (previously a loose column) to orders
-- =============================================================================
ALTER TABLE stock_movements
    ADD CONSTRAINT fk_stock_movements_order
        FOREIGN KEY (order_id) REFERENCES orders(id);

COMMENT ON CONSTRAINT fk_stock_movements_order ON stock_movements IS
    'Links inventory movements created by sales or cancellations to their source order.';
