package com.dietetica.lembas.inventory.dto;

import java.math.BigDecimal;

/** Response returned after confirming a merchandise receipt and generating stock. */
public record PurchaseReceiptDto(
        Long stockLotId,
        StockLotDto stockLot,
        BigDecimal totalAvailableForProductBranch
) {
    /** Creates a receipt response from the stock lot generated by confirmation. */
    public static PurchaseReceiptDto fromStockLot(StockLotDto stockLot) {
        return new PurchaseReceiptDto(
                stockLot.id(),
                stockLot,
                stockLot.totalAvailableForProductBranch()
        );
    }
}
